'''Error definitions.

   Defines integer IDs and error text for errors that might be generated by
   the TWS client.
'''

__copyright__ = "Copyright (c) 2008 Kevin J Bluck"
__version__   = "$Id$"


NO_VALID_ID = -1   # Constant


class TwsError(StandardError):
    '''Wraps a Tws error code identifier and error text as a Python exception.'''

    def __init__(self, id=NO_VALID_ID, code=None, msg=None, source=None):
        assert isinstance(id, int)
        assert (isinstance(code, int) or code is None)
        assert (isinstance(msg, str) or msg is None)
        assert (isinstance(source, TwsError) or source is None)

        StandardError.__init__(self, (id, code, msg, source))

        self._id = id
        self._code = source.code() if source else code
        self._msg = ((("%s %s" % (source.msg(), msg)) if msg else source.msg())
                        if source else msg)


    def __str__(self):
        return (("TWS Error %d: %s" +
                ((" (ID: %d)" % self._id) if self._id != NO_VALID_ID else "")) %
                (self._code, self._msg))


    def id(self):
        return self._id


    def code(self):
        return self._code


    def msg(self):
        return self._msg


# Alias exception type with name defined in Java sources
CodeMsgPair = TwsError


ALREADY_CONNECTED = CodeMsgPair(code=501, msg="Already connected.")
CONNECT_FAIL = CodeMsgPair(code=502, msg="Couldn't connect to TWS.  Confirm that \"Enable ActiveX and Socket Clients\" is enabled on the TWS \"Configure->API\" menu.")
UPDATE_TWS = CodeMsgPair(code=503, msg="The TWS is out of date and must be upgraded.")
NOT_CONNECTED = CodeMsgPair(code=504, msg="Not connected")
UNKNOWN_ID = CodeMsgPair(code=505, msg="Fatal Error: Unknown message id.")
FAIL_SEND_REQMKT = CodeMsgPair(code=510, msg="Request Market Data Sending Error - ")
FAIL_SEND_CANMKT = CodeMsgPair(code=511, msg="Cancel Market Data Sending Error - ")
FAIL_SEND_ORDER = CodeMsgPair(code=512, msg="Order Sending Error - ")
FAIL_SEND_ACCT = CodeMsgPair(code=513, msg="Account Update Request Sending Error -")
FAIL_SEND_EXEC = CodeMsgPair(code=514, msg="Request For Executions Sending Error -")
FAIL_SEND_CORDER = CodeMsgPair(code=515, msg="Cancel Order Sending Error -")
FAIL_SEND_OORDER = CodeMsgPair(code=516, msg="Request Open Order Sending Error -")
UNKNOWN_CONTRACT = CodeMsgPair(code=517, msg="Unknown contract. Verify the contract details supplied.")
FAIL_SEND_REQCONTRACT = CodeMsgPair(code=518, msg="Request Contract Data Sending Error - ")
FAIL_SEND_REQMKTDEPTH = CodeMsgPair(code=519, msg="Request Market Depth Sending Error - ")
FAIL_SEND_CANMKTDEPTH = CodeMsgPair(code=520, msg="Cancel Market Depth Sending Error - ")
FAIL_SEND_SERVER_LOG_LEVEL = CodeMsgPair(code=521, msg="Set Server Log Level Sending Error - ")
FAIL_SEND_FA_REQUEST = CodeMsgPair(code=522, msg="FA Information Request Sending Error - ")
FAIL_SEND_FA_REPLACE = CodeMsgPair(code=523, msg="FA Information Replace Sending Error - ")
FAIL_SEND_REQSCANNER = CodeMsgPair(code=524, msg="Request Scanner Subscription Sending Error - ")
FAIL_SEND_CANSCANNER = CodeMsgPair(code=525, msg="Cancel Scanner Subscription Sending Error - ")
FAIL_SEND_REQSCANNERPARAMETERS = CodeMsgPair(code=526, msg="Request Scanner Parameter Sending Error - ")
FAIL_SEND_REQHISTDATA = CodeMsgPair(code=527, msg="Request Historical Data Sending Error - ")
FAIL_SEND_CANHISTDATA = CodeMsgPair(code=528, msg="Request Historical Data Sending Error - ")
FAIL_SEND_REQRTBARS = CodeMsgPair(code=529, msg="Request Real-time Bar Data Sending Error - ")
FAIL_SEND_CANRTBARS = CodeMsgPair(code=530, msg="Cancel Real-time Bar Data Sending Error - ")
FAIL_SEND_REQCURRTIME = CodeMsgPair(code=531, msg="Request Current Time Sending Error - ")
FAIL_SEND_REQFUNDDATA = CodeMsgPair(code=532, msg="Request Fundamental Data Sending Error - ")
FAIL_SEND_CANFUNDDATA = CodeMsgPair(code=533, msg="Cancel Fundamental Data Sending Error - ")
FAIL_SEND_REQCALCIMPLIEDVOLAT = CodeMsgPair(534, msg="Request Calculate Implied Volatility Sending Error - ")
FAIL_SEND_REQCALCOPTIONPRICE = CodeMsgPair(535, msg="Request Calculate Option Price Sending Error - ")
FAIL_SEND_CANCALCIMPLIEDVOLAT = CodeMsgPair(536, msg="Cancel Calculate Implied Volatility Sending Error - ")
FAIL_SEND_CANCALCOPTIONPRICE = CodeMsgPair(537, msg="Cancel Calculate Option Price Sending Error - ")
FAIL_SEND_REQGLOBALCANCEL = CodeMsgPair(538, msg="Request Global Cancel Sending Error - ")
