'''Error definitions.

   Defines integer IDs and error text for errors that might be generated by
   the TWS client.
'''

__copyright__ = "Copyright (c) 2008 Kevin J Bluck"
__version__   = "$Id$"


class CodeMsgPair(tuple):
    '''Wraps an error code identifier and error text as a tuple.'''

    def __init__(self, pair):
        assert issubclass(type(pair), tuple)
        assert 2 == len(pair)
        assert issubclass(type(pair[0]), int)
        assert issubclass(type(pair[1]), str)

        tuple.__init__(pair)

    def code(self):
        return self[0]

    def msg(self):
        return self[1]


NO_VALID_ID = -1
ALREADY_CONNECTED = CodeMsgPair((501, "Already connected."))
CONNECT_FAIL = CodeMsgPair((502, "Couldn't connect to TWS.  Confirm that \"Enable ActiveX and Socket Clients\" is enabled on the TWS \"Configure->API\" menu."))
UPDATE_TWS = CodeMsgPair((503, "The TWS is out of date and must be upgraded."))
NOT_CONNECTED = CodeMsgPair((504, "Not connected"))
UNKNOWN_ID = CodeMsgPair((505, "Fatal Error: Unknown message id."))
FAIL_SEND_REQMKT = CodeMsgPair((510, "Request Market Data Sending Error - "))
FAIL_SEND_CANMKT = CodeMsgPair((511, "Cancel Market Data Sending Error - "))
FAIL_SEND_ORDER = CodeMsgPair((512, "Order Sending Error - "))
FAIL_SEND_ACCT = CodeMsgPair((513, "Account Update Request Sending Error -"))
FAIL_SEND_EXEC = CodeMsgPair((514, "Request For Executions Sending Error -"))
FAIL_SEND_CORDER = CodeMsgPair((515, "Cancel Order Sending Error -"))
FAIL_SEND_OORDER = CodeMsgPair((516, "Request Open Order Sending Error -"))
UNKNOWN_CONTRACT = CodeMsgPair((517, "Unknown contract. Verify the contract details supplied."))
FAIL_SEND_REQCONTRACT = CodeMsgPair((518, "Request Contract Data Sending Error - "))
FAIL_SEND_REQMKTDEPTH = CodeMsgPair((519, "Request Market Depth Sending Error - "))
FAIL_SEND_CANMKTDEPTH = CodeMsgPair((520, "Cancel Market Depth Sending Error - "))
FAIL_SEND_SERVER_LOG_LEVEL = CodeMsgPair((521, "Set Server Log Level Sending Error - "))
FAIL_SEND_FA_REQUEST = CodeMsgPair((522, "FA Information Request Sending Error - "))
FAIL_SEND_FA_REPLACE = CodeMsgPair((523, "FA Information Replace Sending Error - "))
FAIL_SEND_REQSCANNER = CodeMsgPair((524, "Request Scanner Subscription Sending Error - "))
FAIL_SEND_CANSCANNER = CodeMsgPair((525, "Cancel Scanner Subscription Sending Error - "))
FAIL_SEND_REQSCANNERPARAMETERS = CodeMsgPair((526, "Request Scanner Parameter Sending Error - "))
FAIL_SEND_REQHISTDATA = CodeMsgPair((527, "Request Historical Data Sending Error - "))
FAIL_SEND_CANHISTDATA = CodeMsgPair((528, "Request Historical Data Sending Error - "))
FAIL_SEND_REQRTBARS = CodeMsgPair((529, "Request Real-time Bar Data Sending Error - "))
FAIL_SEND_CANRTBARS = CodeMsgPair((530, "Cancel Real-time Bar Data Sending Error - "))
FAIL_SEND_REQCURRTIME = CodeMsgPair((531, "Request Current Time Sending Error - "))
FAIL_SEND_REQFUNDDATA = CodeMsgPair((532, "Request Fundamental Data Sending Error - "))
FAIL_SEND_CANFUNDDATA = CodeMsgPair((533, "Cancel Fundamental Data Sending Error - "))
